### ISSUE TITLE
Blank Page after modified template

### ISSUE THREAD

**Issue by jricaldi** [NucleusIDE/meteor-live-update#8]
After change something in any template the page refreshed but show a blank page.

**Comment by channikhabra** [comment]
Hey,

I've rewritten this package to be used as a library for pushing code to meteor. For using hot-push in your app, please use these two: [meteor-hot-loader](https://github.com/channikhabra/meteor-hot-loader) and [channikhabra:hot-loader](https://github.com/channikhabra/channikhabra-hot-loader)
